name: Fetch Volume Snapshots

on:
  schedule:
    - cron: '0 11,23 * * *'
  workflow_dispatch:

concurrency:
  group: fetch-volume-snapshots
  cancel-in-progress: false

jobs:
  run-pipeline:
    runs-on: ubuntu-22.04
    timeout-minutes: 55

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_pipeline.txt

      - name: Run pipeline
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          # Optional overrides
          # CHUNK_SIZE: '40'
          # YF_PERIOD: '5d'
          # YF_INTERVAL: '1d'
        run: |
          python -m pipeline.run --log-level INFO
